apiVersion: v2
type: application
appVersion: latest
description: A Matrix-Signal puppeting bridge.
name: mautrix-twitter
version: 0.0.1
keywords:
  - synapse
  - chat
  - matrix
  - twitter
home: https://github.com/tulir/mautrix-twitter
sources:
  - https://github.com/matrix-org/synapse
maintainers:
  - name: Gavin Mogan
    email: helm@gavinmogan.com
