apiVersion: v2
type: application
appVersion: latest@sha256:d365099c4676e246e2d3bce33d3feaee6d1c39835e402ae36ea22e2b3eb1d1a1
description: A Matrix-Twitter puppeting bridge.
name: mautrix-twitter
version: 1.0.2
keywords:
  - synapse
  - chat
  - matrix
  - twitter
  - bridge
home: https://github.com/mautrix/twitter
sources:
  - https://github.com/mautrix/twitter
maintainers:
  - name: Gavin Mogan
    email: helm@gavinmogan.com
annotations:
  artifacthub.io/changes: |2
     - "pin sha so renovate can update it ([70a5575](https://github.com/halkeye-helm-charts/mautrix-twitter/commit/70a5575020b9ce258754af52d06ded60bdb6d689))"
  artifacthub.io/containsSecurityUpdates: 'false'
  artifacthub.io/images: |
    - name: mautrix-googlechat
      image: "dock.mau.dev/mautrix/twitter:latest"
